### PR TITLE
chore(ci): run checks every 12h

### PR DESCRIPTION
**Pull request by vladfrangu**

### CODE REVIEW

**Comment by B4nan** [comment]
I still believe this won't help us at all, we have daily renovate lockfile updates, that's where we bring in new dependencies (and run tests on them). Rerunning the tests periodically with the same lockfile won't uncover anything.

**Review by mtrunkat — APPROVED** [review]
Nice.

**Comment by vladfrangu** [comment]
> I still believe this won't help us at all, we have daily renovate lockfile updates, that's where we bring in new dependencies (and run tests on them). Rerunning the tests periodically with the same lockfile won't uncover anything.

Hmm, good point. We should probably make a separate workflow that runs every 12h that simulates just installing the cli, creating an actor, pushing it, calling it, and nuking it. Thoughts?

**Comment by B4nan** [comment]
i will close this one, as it wouldnt really help with the problem it was trying to solve

**Pull request closed without merging**
