### PR TITLE
fix: prevent running `apify push` from non-actor-looking folders

### LINKED ISSUE #317: `apify push` works in any, even empty folder
It should at least check for the existence of `package.json`, `.actor` folder or something.

### PR DESCRIPTION
**Pull request by vladfrangu**
Closes #317 

Do we want to maybe make the checks stricter? Should we only allow `push` from a directory that has a `.actor` folder / `actor.json` in it?

### CODE REVIEW

**Comment by metalwarrior665** [comment]
I think that's fine, not sure how it even works without one? Later I would want to figure out how to make `apify push` work with monorepos but not a priority now.

**Review by B4nan — APPROVED** [review]
Looking good. We could add a `--cwd` option to allow specifying the path explicitly, that would cover monorepos I guess?

**Comment by metalwarrior665** [comment]
That's not enough. Dockerfile is always in a different folder than the code (usually in the /shared). There are 2 types of monorepos. One has /packages and /actors both with code in separate folders
https://github.com/apify/actor-monorepo-example

Other has only single /code and /actors have just Dockerfile, .actor and Readme.
https://github.com/apify-projects/store-google-search

**Comment by B4nan** [comment]
So how are you doing it now in those two cases? I thought the location of the dockerfile is not important as its linked from the actor.json?

**Comment by metalwarrior665** [comment]
Currently, we don't do it at all, the only idea I had is to have a script that will re-structure the files before pushing them to Apify

**Pull request merged**
