### PR TITLE
feat: Update api token links

### PR DESCRIPTION
**Pull request by valekjo**
This PR updates links to settings > integrations page in console.

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Review by katacek — APPROVED** [review]
🚀

**Review by TC-MO — APPROVED** [review]
LGTM, should the same change be done in other repos?

**Comment by valekjo** [comment]
> LGTM, should the same change be done in other repos?

Yes, I think we already did that in most.

**Comment by TC-MO** [comment]
> > LGTM, should the same change be done in other repos?
> 
> Yes, I think we already did that in most.

I'll double check cause I am pretty sure that I found a few occurences in platform docs, thanks!

**Pull request merged**
