### PR TITLE
chore: unify subnavs + placeholder reference

### PR DESCRIPTION
**Pull request by barjin**

### CODE REVIEW

**Comment by barjin** [comment]
The /examples / /docs are rather placeholder-y too, they also need some attention (make the docs more detailed + comprehensive)

**Review by B4nan — COMMENTED** [review]
i'll review the content more carefully once its deployed, generally i'd use the `npx` variants everywhere and we should have a section about the installation, mentioning npx, updating, global npm install, maybe yarn/pnpm as well

**Comment by B4nan** [comment]
Is this still valid? If so we should rebase+merge.

**Comment by barjin** [comment]
huh, seems like we don't need this anymore, as it's pretty much identical to #330 ... the docs are not exactly extensive now, so there is no need for splitting them into Guides / Examples now 🤔

**Comment by B4nan** [comment]
Ok if you see something worth backporting, please do so.

**Pull request closed without merging**
