### PR TITLE
feat: `key-value-stores get-value`

### PR DESCRIPTION
**Pull request by vladfrangu**
Code - 2024-10-07 at 16 03 30@2x

### CODE REVIEW

**Comment by B4nan** [comment]
I believe we agreed that datasets should go first.

**Comment by vladfrangu** [comment]
> I believe we agreed that datasets should go first.

thats also coming in a few minutes 😄

**Comment by B4nan** [comment]
also it feels weird to print the response without any formatting, can we at least use spacing/line breaks? or maybe even `util.inspect` with colors enabled?

**Comment by vladfrangu** [comment]
We shouldn't do any formatting to the output, as not all items have a JSON body, so it can cause issues...

As it stands, the content-type is emitted to stderr, the item itself to stdout (like @netmilk  requested in the epic)... Not sure if it needs to have anything fancier than that 👀

**Review by B4nan — APPROVED** [review]

**Pull request merged**
